#!/bin/bash

GET() {
	curl -Lk -XGET ${ENDPOINT}${1}
}
PUT() {
	curl -Lk -XPUT -u "${AUTH_USER}:${AUTH_PASS}" ${ENDPOINT}${1} --data "${2}" -H 'Content-type: application/json'
}
POST() {
	curl -Lk -XPOST -u "${AUTH_USER}:${AUTH_PASS}" ${ENDPOINT}${1} --data "${2}" -H 'Content-type: application/json'
}
DELETE() {
	curl -Lk -XDELETE -u "${AUTH_USER}:${AUTH_PASS}"  ${ENDPOINT}${1}
}

ENDPOINT=$1  ; shift
AUTH_USER=$1 ; shift
AUTH_PASS=$1 ; shift
if [[ -z $ENDPOINT || -z $AUTH_USER || -z $AUTH_PASS || -n $1 ]]; then
	echo >&2 "USAGE: $0 <url> <user> <pass>"
	exit 1
fi

for stemcell in \
	bosh-aws-xen-hvm-ubuntu-trusty-go_agent \
	bosh-aws-xen-ubuntu-trusty-go_agent \
	bosh-azure-hyperv-ubuntu-trusty-go_agent \
	bosh-openstack-kvm-ubuntu-trusty-go_agent \
	bosh-openstack-kvm-ubuntu-trusty-go_agent-raw \
	bosh-vcloud-esxi-ubuntu-trusty-go_agent \
	bosh-vsphere-esxi-ubuntu-trusty-go_agent \
	bosh-warden-boshlite-ubuntu-trusty-go_agent
do
	POST '/v1/stemcell' '{"name":"'${stemcell}'","url":"https://bosh.io/d/stemcells/'${stemcell}'?v={{version}}"}'
done

for cpi in aws azure openstack rackhd softlayer vcloud vsphere google
do
	POST '/v1/release' '{"name":"bosh-'${cpi}'-cpi","url":"https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-'${cpi}'-cpi-release?v={{version}}"}'
done

for release in \
	bind9 \
	cf-haproxy cf-subway consul \
	docker-registry \
	jumpbox \
	route-registrar \
	shell \
	toolbelt \
	vault \
	prometheus \
	sawmill \
	simple-remote-syslog \
	slack-notification-resource
do
	POST '/v1/release' '{"name":"'${release}'","url":"https://bosh.io/d/github.com/cloudfoundry-community/'${release}'-boshrelease?v={{version}}"}'
done

for release in \
	cloudfoundry/cf-release \
	cloudfoundry/cf-mysql-release \
	cloudfoundry/bosh \
	cloudfoundry/uaa-release \
	pivotal-cf/cf-rabbitmq-release \
	pivotal-cf/cf-redis-release \
	cloudfoundry-incubator/diego-release \
	cloudfoundry-incubator/etcd-release \
	cloudfoundry-incubator/garden-linux-release \
	cloudfoundry-incubator/garden-runc-release \
	cf-platform-eng/docker-release \
	concourse/concourse \
	cppforlife/bosh-warden-cpi-release \
	hybris/nxlog-boshrelease \
	dpb587/openvpn-bosh-release
do
	POST '/v1/release' '{"name":"'${release}'","url":"https://bosh.io/d/github.com/'${release}'?v={{version}}"}'
done

for release in \
	shield
do
	POST '/v1/release' '{"name":"'${release}'","url":"https://bosh.io/d/github.com/starkandwayne/'${release}'-boshrelease?v={{version}}"}'
done

for release in \
	bolo \
	postgres \
	port-forwarding \
	strongswan \
	netdata \
	tmate
do
	POST '/v1/release' '{"name":"'${release}'","url":"https://github.com/cloudfoundry-community/'${release}'-boshrelease/releases/download/v{{version}}/'${release}'-{{version}}.tgz"}'
done

for release in \
	dingotiles/dingo-postgresql-release
do
	POST '/v1/release' '{"name":"'${release}'","url":"https://github.com/'${release}'/releases/download/v{{version}}/'${release}'-{{version}}.tgz"}'
done

echo "DONE"
